// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	persistence "github.com/isaacmirandacampos/dreamkoffee/internal/storage/persistence"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateExpense mocks base method.
func (m *MockRepository) CreateExpense(ctx context.Context, arg persistence.CreateExpenseParams) (persistence.Expense, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateExpense", ctx, arg)
	ret0, _ := ret[0].(persistence.Expense)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateExpense indicates an expected call of CreateExpense.
func (mr *MockRepositoryMockRecorder) CreateExpense(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateExpense", reflect.TypeOf((*MockRepository)(nil).CreateExpense), ctx, arg)
}

// DeleteExpense mocks base method.
func (m *MockRepository) DeleteExpense(ctx context.Context, id int32) (persistence.Expense, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpense", ctx, id)
	ret0, _ := ret[0].(persistence.Expense)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpense indicates an expected call of DeleteExpense.
func (mr *MockRepositoryMockRecorder) DeleteExpense(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpense", reflect.TypeOf((*MockRepository)(nil).DeleteExpense), ctx, id)
}

// GetExpense mocks base method.
func (m *MockRepository) GetExpense(ctx context.Context, id int32) (persistence.Expense, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExpense", ctx, id)
	ret0, _ := ret[0].(persistence.Expense)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExpense indicates an expected call of GetExpense.
func (mr *MockRepositoryMockRecorder) GetExpense(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExpense", reflect.TypeOf((*MockRepository)(nil).GetExpense), ctx, id)
}

// GetLastExpense mocks base method.
func (m *MockRepository) GetLastExpense(ctx context.Context) (persistence.Expense, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastExpense", ctx)
	ret0, _ := ret[0].(persistence.Expense)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastExpense indicates an expected call of GetLastExpense.
func (mr *MockRepositoryMockRecorder) GetLastExpense(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastExpense", reflect.TypeOf((*MockRepository)(nil).GetLastExpense), ctx)
}

// ListExpenses mocks base method.
func (m *MockRepository) ListExpenses(ctx context.Context) ([]persistence.Expense, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExpenses", ctx)
	ret0, _ := ret[0].([]persistence.Expense)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListExpenses indicates an expected call of ListExpenses.
func (mr *MockRepositoryMockRecorder) ListExpenses(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExpenses", reflect.TypeOf((*MockRepository)(nil).ListExpenses), ctx)
}

// UpdateExpense mocks base method.
func (m *MockRepository) UpdateExpense(ctx context.Context, arg persistence.UpdateExpenseParams) (persistence.Expense, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateExpense", ctx, arg)
	ret0, _ := ret[0].(persistence.Expense)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateExpense indicates an expected call of UpdateExpense.
func (mr *MockRepositoryMockRecorder) UpdateExpense(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateExpense", reflect.TypeOf((*MockRepository)(nil).UpdateExpense), ctx, arg)
}
