// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/shopspring/decimal"
)

type Expense struct {
	ID          int             `json:"id"`
	Description string          `json:"description"`
	Value       decimal.Decimal `json:"value"`
	CreatedAt   string          `json:"createdAt"`
	UpdatedAt   string          `json:"updatedAt"`
}

type Income struct {
	ID          int             `json:"id"`
	Description string          `json:"description"`
	Value       decimal.Decimal `json:"value"`
	CreatedAt   string          `json:"createdAt"`
	UpdatedAt   string          `json:"updatedAt"`
}

type Mutation struct {
}

type NewExpense struct {
	Description string          `json:"description"`
	Value       decimal.Decimal `json:"value"`
}

type NewIncome struct {
	Description string          `json:"description"`
	Value       decimal.Decimal `json:"value"`
}

type Query struct {
}

type UpdateExpense struct {
	Description string          `json:"description"`
	Value       decimal.Decimal `json:"value"`
}

type UpdateIncome struct {
	Description string          `json:"description"`
	Value       decimal.Decimal `json:"value"`
}
