package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"log"

	"github.com/isaacmirandacampos/finkoffee/internal/interface/graphql/model"
	"github.com/isaacmirandacampos/finkoffee/internal/storage/persistence"
)

// CreateExpense is the resolver for the createExpense field.
func (r *mutationResolver) CreateExpense(ctx context.Context, input model.NewExpense) (*model.Expense, error) {
	// resolve unexpected type json.Number for Decimal
	log.Printf("input.Price: %T", input.Price)
	log.Printf("input.Price: %v", input.Price)
	expense := &model.Expense{
		Name:  input.Name,
		Price: input.Price,
	}

	inserted, err := r.Conn.CreateExpense(ctx, persistence.CreateExpenseParams{
		Name:  expense.Name,
		Price: expense.Price,
	})

	if err != nil {
		return nil, err
	}
	newExpense := &model.Expense{
		ID:        int(inserted.ID),
		Price:     inserted.Price,
		Name:      inserted.Name,
		CreatedAt: inserted.CreatedAt.String(),
		UpdatedAt: inserted.UpdatedAt.String(),
	}
	return newExpense, nil
}

// Expenses is the resolver for the expenses field.
func (r *queryResolver) Expenses(ctx context.Context) ([]*model.Expense, error) {
	expenses, err := r.Conn.ListExpenses(ctx)
	if err != nil {
		return nil, err
	}

	var result []*model.Expense
	for _, expense := range expenses {
		result = append(result, &model.Expense{
			ID:        int(expense.ID),
			Name:      expense.Name,
			Price:     expense.Price,
			CreatedAt: expense.CreatedAt.String(),
			UpdatedAt: expense.UpdatedAt.String(),
		})
	}

	return result, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
