package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/isaacmirandacampos/finkoffee/internal/interface/graphql/model"
	"github.com/isaacmirandacampos/finkoffee/internal/usescases/expense"
)

func (r *mutationResolver) CreateExpense(ctx context.Context, input model.NewExpense) (*model.Expense, error) {
	new_expense, err := expense.NewExpenseUseCase(r.Conn).CreateExpense(ctx, input)
	if err != nil {
		return nil, err
	}
	return new_expense, nil
}

func (r *mutationResolver) UpdateExpense(ctx context.Context, id int, input model.UpdateExpense) (*model.Expense, error) {
	updated_expense, err := expense.NewExpenseUseCase(r.Conn).UpdateExpense(ctx, &id, input)
	if err != nil {
		return nil, err
	}
	return updated_expense, nil
}

func (r *queryResolver) ListExpense(ctx context.Context) ([]*model.Expense, error) {
	expenses, err := expense.NewExpenseUseCase(r.Conn).ListExpenses(ctx)
	if err != nil {
		return nil, err
	}
	return expenses, nil
}

func (r *queryResolver) GetExpense(ctx context.Context, id int) (*model.Expense, error) {
	expense, err := expense.NewExpenseUseCase(r.Conn).GetExpenses(ctx, &id)
	if err != nil {
		return nil, err
	}
	return expense, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
