// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/shopspring/decimal"
)

type Expense struct {
	ID        int             `json:"id"`
	Price     decimal.Decimal `json:"price"`
	Name      string          `json:"name"`
	CreatedAt string          `json:"createdAt"`
	UpdatedAt string          `json:"updatedAt"`
}

type Mutation struct {
}

type NewExpense struct {
	Price decimal.Decimal `json:"price"`
	Name  string          `json:"name"`
}

type Query struct {
}
