// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewTransaction struct {
	Amount      float64 `json:"amount"`
	Description string  `json:"description"`
}

type Query struct {
}

type Transaction struct {
	ID          string  `json:"id"`
	Amount      float64 `json:"amount"`
	Description string  `json:"description"`
	CreatedAt   string  `json:"createdAt"`
}
