CREATE TABLE IF NOT EXISTS expenses (
  id SERIAL PRIMARY KEY,
  value NUMERIC(10,2) NOT NULL,
  description VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMP WITH TIME ZONE
);