// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package persistence

import (
	"database/sql"
	"time"

	"github.com/shopspring/decimal"
)

type Expense struct {
	ID          int32           `db:"id" json:"id"`
	Value       decimal.Decimal `db:"value" json:"value"`
	Description string          `db:"description" json:"description"`
	CreatedAt   time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time       `db:"updated_at" json:"updated_at"`
	DeletedAt   sql.NullTime    `db:"deleted_at" json:"deleted_at"`
}
