// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package persistence

import (
	"context"
)

type Querier interface {
	CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error)
	DeleteExpense(ctx context.Context, id int32) (Expense, error)
	GetExpense(ctx context.Context, id int32) (Expense, error)
	GetLastExpense(ctx context.Context) (Expense, error)
	ListExpenses(ctx context.Context) ([]Expense, error)
	UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error)
}

var _ Querier = (*Queries)(nil)
