package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"

	"github.com/isaacmirandacampos/finkoffee/internal/applications/graph/model"
)

// CreateIncome is the resolver for the createIncome field.
func (r *mutationResolver) CreateIncome(ctx context.Context, input model.NewIncome) (*model.Income, error) {
	panic(fmt.Errorf("not implemented: CreateIncome - createIncome"))
}

// UpdateIncome is the resolver for the updateIncome field.
func (r *mutationResolver) UpdateIncome(ctx context.Context, id int, input model.UpdateIncome) (*model.Income, error) {
	panic(fmt.Errorf("not implemented: UpdateIncome - updateIncome"))
}

// ListIncome is the resolver for the listIncome field.
func (r *queryResolver) ListIncome(ctx context.Context) ([]*model.Income, error) {
	panic(fmt.Errorf("not implemented: ListIncome - listIncome"))
}

// GetIncome is the resolver for the getIncome field.
func (r *queryResolver) GetIncome(ctx context.Context, id int) (*model.Income, error) {
	panic(fmt.Errorf("not implemented: GetIncome - getIncome"))
}
