// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/shopspring/decimal"
)

type Authentication struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type AuthenticationResponse struct {
	Success bool `json:"success"`
}

type Expense struct {
	ID          int             `json:"id"`
	Description string          `json:"description"`
	Value       decimal.Decimal `json:"value"`
	PaidAt      string          `json:"paidAt"`
	Note        string          `json:"note"`
	PaymentAt   string          `json:"paymentAt"`
	CreatedAt   string          `json:"createdAt"`
	UpdatedAt   string          `json:"updatedAt"`
}

type Mutation struct {
}

type NewExpense struct {
	Description string          `json:"description"`
	Value       decimal.Decimal `json:"value"`
	PaidAt      *string         `json:"paidAt,omitempty"`
	PaymentAt   *string         `json:"paymentAt,omitempty"`
	Note        *string         `json:"note,omitempty"`
}

type NewUser struct {
	FullName string `json:"full_name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Query struct {
}

type UpdateExpense struct {
	Description string          `json:"description"`
	Value       decimal.Decimal `json:"value"`
	Note        *string         `json:"note,omitempty"`
	PaidAt      *string         `json:"paidAt,omitempty"`
	PaymentAt   *string         `json:"paymentAt,omitempty"`
}

type User struct {
	ID        int    `json:"id"`
	FullName  string `json:"full_name"`
	Email     string `json:"email"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}
